### ISSUE TITLE
performance comparison

### ISSUE THREAD

**Issue by MikeMitterer** [ltackmann/dice#22]
Have you ever compared the performance between dice and di?

**Comment by ltackmann** [comment]
No, would be interested in knowing the results though. Also I am considering a shift to reflectable instead of mirror based approach where possible, not sure how that will impact performance.

**Comment by MikeMitterer** [comment]
I switch my MDL library and all its samples over to Dice.
Here a short and simple stat I made with `time pub build`

**Dice**
Took 0:00:17.785300 to compile mdl_styleguide|web/main.dart.
Built 544 files to "build".

real	0m30.490s
user	0m30.461s
sys	0m2.678s

main.dart.js 792K

**DI**
Took 0:00:14.205555 to compile mdl_styleguide|web/main.dart.
Built 551 files to "build".

real	0m24.630s
user	0m36.189s
sys	0m3.066s
main.dart.js 779.2K

OK DI is 2secs faster but the error messages in Dice are much clearer. Until now I'm very happy with your lib. On Monday I'll switch over all my internal libs.

**Comment by ltackmann** [comment]
Thanks for the numbers and the pull requests, keep it coming
