### ISSUE TITLE
Inherited injectable properties are not resolved.

### ISSUE THREAD

**Issue by KOGI** [ltackmann/dice#28]
`injector.resolveInjections()` uses `classMirror.declarations` to obtain a list of all injectable variables on a class. However, [`classMirror.declarations` doesn't include inherited properties](https://api.dartlang.org/stable/1.24.3/dart-mirrors/ClassMirror/declarations.html) as such, the following injection is never resolved:

```dart
class Foo extends Bar {
  Foo():super();
}

class Bar {
  @inject Zap myInjectedProperty;

  Bar() {
    // setup
  }
}

var bar = new Bar();
print(bar.myInjectedProperty); // <<-- instance of Zap

var foo = new Foo();
print(foo.myInjectedProperty); // <<-- null
```

**Comment by ltackmann** [comment]
Should be fixed by pull request. @MikeMitterer previously asked if he could take over this project as I have little time.
